import type { Exercise } from "./types.js";

export const EXERCISES: Exercise[] = [
  {
    key: "squat",
    name: "Bodyweight squat",
    discipline: "gym",
    trackingMode: "hybrid",
    successMetric: "reps",
    met: 5.0,
    visionSupported: true,
    defaultReps: 8,
    defaultHold: 0,
    defaultWork: 0,
    defaultRest: 45,
    cues: "Sit back, knees track over toes, stand tall.",
  },
  {
    key: "push_up",
    name: "Push-up",
    discipline: "gym",
    trackingMode: "hybrid",
    successMetric: "reps",
    met: 3.8,
    visionSupported: true,
    defaultReps: 6,
    defaultHold: 0,
    defaultWork: 0,
    defaultRest: 45,
    cues: "Body in a line, chest close to the floor, lock out elbows.",
  },
  {
    key: "lunge",
    name: "Forward lunge",
    discipline: "gym",
    trackingMode: "hybrid",
    successMetric: "reps",
    met: 4.0,
    visionSupported: true,
    defaultReps: 8,
    defaultHold: 0,
    defaultWork: 0,
    defaultRest: 45,
    cues: "Front knee over mid-foot, back knee lowers with control.",
  },
  {
    key: "jumping_jack",
    name: "Jumping jack",
    discipline: "gym",
    trackingMode: "hybrid",
    successMetric: "reps",
    met: 8.0,
    visionSupported: true,
    defaultReps: 20,
    defaultHold: 0,
    defaultWork: 30,
    defaultRest: 20,
    cues: "Arms and legs open together, land softly.",
  },
  {
    key: "crunch",
    name: "Crunch",
    discipline: "gym",
    trackingMode: "hybrid",
    successMetric: "reps",
    met: 3.8,
    visionSupported: true,
    defaultReps: 10,
    defaultHold: 0,
    defaultWork: 0,
    defaultRest: 30,
    cues: "Ribs toward hips, keep neck long.",
  },
  {
    key: "plank",
    name: "Plank",
    discipline: "gym",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 3.8,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 20,
    defaultWork: 0,
    defaultRest: 30,
    cues: "Shoulders over elbows, hips in line with shoulders and heels.",
  },
  {
    key: "mountain",
    name: "Mountain pose",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 2.5,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 30,
    defaultWork: 0,
    defaultRest: 10,
    cues: "Stand tall, weight even on both feet, shoulders relaxed.",
  },
  {
    key: "downward_dog",
    name: "Downward-facing dog",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 2.5,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 40,
    defaultWork: 0,
    defaultRest: 15,
    cues: "Hips high, long spine, heels reaching toward the floor.",
  },
  {
    key: "warrior_ii",
    name: "Warrior II",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 3.0,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 25,
    defaultWork: 0,
    defaultRest: 15,
    cues: "Front knee bent, back leg straight, arms in a T.",
  },
  {
    key: "tree",
    name: "Tree pose",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 2.5,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 20,
    defaultWork: 0,
    defaultRest: 15,
    cues: "Stand on one leg, other foot on inner thigh or calf (not the knee).",
  },
  {
    key: "cobra",
    name: "Cobra pose",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 2.5,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 20,
    defaultWork: 0,
    defaultRest: 15,
    cues: "Hands under shoulders, lift chest, hips stay heavy.",
  },
  {
    key: "chair",
    name: "Chair pose",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 3.5,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 20,
    defaultWork: 0,
    defaultRest: 15,
    cues: "Sit back, knees track forward, arms reach up.",
  },
  {
    key: "triangle",
    name: "Triangle pose",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 2.5,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 25,
    defaultWork: 0,
    defaultRest: 15,
    cues: "Long stance, front leg straight, torso opens to the side.",
  },
  {
    key: "child",
    name: "Child's pose",
    discipline: "yoga",
    trackingMode: "hybrid",
    successMetric: "hold_seconds",
    met: 2.0,
    visionSupported: true,
    defaultReps: 0,
    defaultHold: 30,
    defaultWork: 0,
    defaultRest: 10,
    cues: "Hips to heels, arms reach forward or rest by the sides.",
  },
  {
    key: "march_in_place",
    name: "March in place",
    discipline: "other",
    trackingMode: "timer",
    successMetric: "work_seconds",
    met: 3.5,
    visionSupported: false,
    defaultReps: 0,
    defaultHold: 0,
    defaultWork: 45,
    defaultRest: 20,
    cues: "Lift knees, swing opposite arms, stay on the clock.",
  },
];

export const EXERCISE_MAP = Object.fromEntries(EXERCISES.map((e) => [e.key, e]));

export function getExercise(key: string): Exercise | undefined {
  return EXERCISE_MAP[key];
}

export function isVisionKey(key: string): boolean {
  return Boolean(getExercise(key)?.visionSupported);
}
